[project]
name = "lynx"
version = "0.1.0"
description = "A desktop app to facilitate the clerical review of linked data."
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["numpy>=2.3.2", "pandas>=2.3.2"]

[dependency-groups]
dev = [
    "commitizen>=4.8.4",
    "pre-commit>=4.3.0",
    "ruff>=0.12.12",
]

[tool.ruff.lint]
select = ["ALL"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
